apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: local-web
  template:
    metadata:
      labels:
        app: local-web
    spec:
      containers:
      - name: local-web
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: local
          mountPath: /usr/share/nginx/html
      volumes:
      - name: local
        hostPath: 
          path: /var/nginxserver
